### ISSUE TITLE
Language plot wrong when not all judgement types present

### ISSUE THREAD

**Issue by eldering** [icpc-live/autoanalyst#24] opened 2016-11-20 14:46 UTC
The (jquery flot) plot of results seems to be wrong when intermediate judgement types are missing for a language, see screenshot. Once Python 3 received a TLE submission, this fixed the plot. I don't know whether this is a bug in our or the flot code. I can provide the icat DB dump on request.

![icat-lang-plot](https://cloud.githubusercontent.com/assets/4692022/20463643/0a6e8b7c-af1f-11e6-8197-3efbbb98c2e6.png)

**Comment by ghamerly** [comment] 2016-11-20 14:58
Seems to be a duplicate of #18 ?

**Closed** 2016-11-20 15:10 UTC
Labels: bug, duplicate, iCAT
